define({
    "_widgetLabel": "数据导入",
    "description": "<a id='data_sample'style='color: blue' href='./widgets/DataLookup/data/点信息导入模板.xls' tooltip='Download an sample sheet' target='_blank'>模板下载</a>",
    "selectCSV": "选择文件",
    "loadingCSV": "加载文件",
    "savingCSV": "ExeclExport",
    "clearResults": "清除",
    "downloadResults": "下载",
    "plotOnly": "仅为绘制点",
    "plottingRows": "绘制行",
    "projectionChoice": "坐标系：",
    "projectionLat": "经纬度",
    "projectionMap": "地图投影",
    "messages": "消息",
    "mapChoice": "类型选择：",
    "normalMap": "普通图",
    "heatMap": "热力图",
    "districtMap": "小区图",
    "gridMap": "栅格图",
    "createHeatmapRenderer": "创建热力图",
    "clearHeatmapRenderer": "清除图层",
    "createNormalRenderer":"唯一值渲染",
    "valueList": "值列：",
    "watchOut": " * 请选择数值列进行生成。",
    "warnOut": "该数据无除坐标信息之外的参数。",
    "magnitude":"按权重",
    "BlurRadius":"模糊半径",
    "MaxValue":"最大像素值",
    "MinValue":"最小像素值",
    "Color":"色带",
    "error": {
        "fetchingCSV": "从文件存储提取项目时出错: ${0}",
        "fileIssue": "无法处理文件。",
        "listAttributes": "该列数据不是数值数据，请选择具有数值列进行热度图的生成。",
        "listWarnAttributes": "该数据无除坐标信息之外的参数。",
        "notCSVFile": "文件格式错误，请检查文件数据格式（支持Excel表格数据）。",
        "invalidCoord": "位置字段无效。请检查文件属性数据格式（请参考可下载的电子表格设置属性）。",
        "tooManyRecords": "抱歉，目前不能超过 ${0} 条记录。",
        "CSVNoRecords": "该文件不包含任何记录。",
        "CSVEmptyFile": "文件中无内容。"
    },
    "results": {
        "csvLoaded": "已从文件中加载 ${0} 条记录",
        "xlsxLoaded": "已从文件中加载 ${0} 条记录",
        "recordsPlotted": "地图上已有 ${0}/${1} 条记录",
        "recordsEnriched": "已处理 ${0}/${1}，已根据 ${3} 丰富 ${2}",
        "recordsError": "${0} 条记录出错",
        "recordsErrorList": "行 ${0} 存在问题",
        "label": "文件结果"
    }
});